# Generated by Django 3.0.7 on 2020-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceTEst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Parsing'), (1, 'Invalid'), (2, 'Parsed')], default=0),
        ),
    ]
