# Generated by Django 3.0.7 on 2020-06-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceTEst', '0003_auto_20200611_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehead',
            name='street_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='invoice_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='small_business_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
